### PR TITLE
Support ckan extras

### LINKED ISSUE #6: Auto detect fields from CKAN package extra data array
## Auto detect fields from CKAN package extra data array

The following fields:
- `contact_point`
- ` license_title`
- ` spatial_coverage`
-  ` temporal_coverage_from `
- ` temporal_coverage_to`

are available on CKAN via plugin [ckanext-dgu](https://github.com/datagovuk/ckanext-dgu) and might be available as "extra" data on CKAN instance without the plugin installed.

image

Those fields are critical for Magda's searching capability (especially, spatial_coverage, temporal_coverage and license_title).

The ckan connector's [field mapping template](https://github.com/magda-io/magda-ckan-connector/tree/master/aspect-templates) should be updated to search for those fields from extra data as well.

### PR DESCRIPTION
**Pull request by jevy-wangfei**
### What this PR does

Fixes #6 

This is a description of what I've done in this PR, especially explaining choices made to make the reviewer's job easier. If I don't replace this paragraph with an actual description, my PR will probably be ignored.

### Checklist

-   [x] There are unit tests to verify my changes are correct or unit tests aren't applicable
-   [x] I've updated CHANGES.md with what I changed.
-   [ ] I've linked this PR to an issue in ZenHub (core dev team only)

### CODE REVIEW

**Comment by t83714** [comment]
Hi @jevy-wangfei how did you go with the testing release?
I am thinking if it's working alright in your deployment, probably it's time for me to merge it and release an offical version.

**Comment by jevy-wangfei** [comment]
> Hi @jevy-wangfei how did you go with the testing release?
> I am thinking if it's working alright in your deployment, probably it's time for me to merge it and release an offical version.

Hi Jacky, 
We have a test instance, and I deployed the alpha.2 release on it for testing.

**Comment by t83714** [comment]
@jevy-wangfei Thanks a lot for excellent work 💯  ~ I also had a quick test in a local cluster and worked well. Merging

**Comment by t83714** [comment]
oops accidentally click the wrong button... fixed & merged now.
A new release v1.1.0 has been created here:  
https://github.com/magda-io/magda-ckan-connector/releases/tag/v1.1.0
Thanks again for your contributions

**Pull request merged**
